name: First Workflow
on: workflow_dispatch #for manually triggering workflows
jobs:
   first-job:
     runs-on: macos-latest
     steps:
       - name: Print greeting
         run: echo "Hello World!"
       - name: Print Goodby
         run: echo "Done-bye!"
        
